<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\FalconPay.FraudShield.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\FalconPay.FraudShield.Infrastructure.csproj" />
  </ItemGroup>

</Project>

